development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: travisonrails_development
  pool: 5
  username: webuser
  password: webuser

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: travisonrails_test
  pool: 5
  username: webuser
  password: webuser

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: travisonrails_production
  pool: 5
  username: travisonrails
  password: tor204828
